version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rev_forum
    volumes:
      - ../shared_folder:/shared_folder
    networks:
      - app-network

  node-app:
    image: node:20
    container_name: node_container
    working_dir: /app
    volumes:
      - ../frontend/rev-front:/app
    ports:
      - "80:5173"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    depends_on:
      - postgres
    networks:
      - app-network


  golang:
    image: golang:latest
    container_name: golang_container
    working_dir: /app  # Абсолютный путь внутри контейнера
    volumes:
      - ../backend:/app  # Монтируем backend в /app
    command: sh -c "go mod tidy && go get gorm.io/driver/postgres && go get github.com/joho/godotenv && go install github.com/joho/godotenv/cmd/godotenv@latest && go get -u gorm.io/gorm && go run main.go && go get github.com/rs/cors"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: